version: "3.9"

services:
  backend:
    image: khilar/tasknet-server:latest
    build: .
    container_name: backend-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
